name: babel-firebird

x-node: &node
    image: node:18-slim
    user: ${CURRENT_USER}
    profiles:
      - node
    volumes:
      - ${BABEL_HOME}/firebird-common:/htapps/babel/firebird-common
      - ${BABEL_HOME}/pt:/htapps/babel/pt
      - ${BABEL_HOME}/.npm:/.npm

services:

  perl-dev:
    build:
      context: .
      target: perl-dev
    volumes:
      - ${BABEL_HOME}:/htapps/babel
      - ${BABEL_HOME}/sample-data/sdr1:/sdr1
      - ${BABEL_HOME}/sample-data/etc:/htapps/babel/etc
      - ${BABEL_HOME}/sample-data/watermarks:/htapps/babel/watermarks
      - ${BABEL_HOME}/sample-data:/tmp/sample-data
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
      - HT_DEV=docker
      - REMOTE_ADDR=127.0.0.1
      - HTTP_HOST=127.0.0.1
      - APACHE_LOG_DIR=/tmp
      - PERL5LIB=/htapps/babel/imgsrv/lib:/htapps/babel/mdp-lib:/htapps/babel/plack-lib:/htapps/babel/slip-lib
    depends_on:
      - mysql-sdr
      - solr-sdr-catalog
      - solr-ptsearch
    command: "/bin/bash"
    stdin_open: true
    tty: true

  imgsrv:
    build:
      context: .
      target: imgsrv-fcgi
    user: ${CURRENT_USER}
    volumes:
      - ${BABEL_HOME}:/htapps/babel
      - ${BABEL_HOME}/sample-data/sdr1:/sdr1
      - ${BABEL_HOME}/sample-data/etc:/htapps/babel/etc
      - ${BABEL_HOME}/sample-data/watermarks:/htapps/babel/watermarks
      - ${BABEL_HOME}/sample-data:/tmp/sample-data
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
      - HT_DEV=docker
      - REMOTE_ADDR=127.0.0.1
      - HTTP_HOST=127.0.0.1
      - APACHE_LOG_DIR=/tmp
    depends_on:
      - mysql-sdr
      - solr-sdr-catalog
    ports:
      - "31028:31028"
    command: bash -c "/htapps/babel/imgsrv/bin/startup_imgsrv"

  apache:
    build:
      context: .
      target: apache
    user: ${CURRENT_USER}
    volumes:
      - ${BABEL_HOME}:/htapps/babel
      - ${BABEL_HOME}/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ${BABEL_HOME}/apache/auth:/etc/apache2/auth
      - ${BABEL_HOME}/sample-data/sdr1:/sdr1
      - ${BABEL_HOME}/sample-data/etc:/htapps/babel/etc
      - ${BABEL_HOME}/sample-data:/tmp/sample-data
      - ${BABEL_HOME}/catalog:/htapps/catalog
      - ${BABEL_HOME}/mb/lib/Config/docker-local.conf:/htapps/babel/mb/lib/Config/local.conf
      - ${BABEL_HOME}/ls/lib/Config/docker-local.conf:/htapps/babel/ls/lib/Config/local.conf

    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
    depends_on:
      - mysql-sdr
      - solr-sdr-catalog
      - solr-ptsearch
      - imgsrv
      - vufind
    ports:
      - "8080:8080"
      - "5173:5173"
      - "8173:8173"

  vufind:
    build: ./catalog
    hostname: 'catalog-dev'
    volumes:
      - ${BABEL_HOME}/catalog:/app
      - ${BABEL_HOME}/firebird-common:/htapps/babel/firebird-common
    environment:
      - FIREBIRD_HOME=/htapps/babel/firebird-common
    depends_on:
      - mysql-sdr
      - solr-sdr-catalog

  firebird:
    <<: *node
    working_dir: /htapps/babel/firebird-common
    command: ['npm', 'run', 'babel']

  page-turner:
    <<: *node
    working_dir: /htapps/babel/pt/web/firebird
    command: ['npm', 'run', 'babel']



### DATA STORES

  solr-sdr-catalog:
    image: ghcr.io/hathitrust/catalog-solr-sample
    ports:
      - "9033:9033"
    volumes:
      - solr_sdr_catalog:/var/solr

  solr-lss-dev:
    image: solr:6.6.6-alpine
    ports:
      - "8983:8983"
    user: ${CURRENT_USER}
    volumes:
      - ${BABEL_HOME}/lss_solr_configs/solr6_standalone/lss-dev/core-x:/opt/solr/server/solr/core-x
      - ${BABEL_HOME}/lss_solr_configs/solr6_standalone/lss-dev/core-y:/opt/solr/server/solr/core-y
      - ${BABEL_HOME}/lss_solr_configs/solr6_standalone:/opt/lss_solr_configs
      - ${BABEL_HOME}/lss_solr_configs/solr6_standalone/lib:/opt/solr/server/solr/lib
      - ${BABEL_HOME}/logs/solr:/opt/solr/server/logs

  solr-ptsearch:
    build: ./ptsearch-solr
    ports:
      - "8984:8983"

  mysql-sdr:
    image: ghcr.io/hathitrust/db-image:latest
    volumes:
      - ${BABEL_HOME}/slip/etc/sql/100_slip.sql:/docker-entrypoint-initdb.d/100_slip.sql
      - ${BABEL_HOME}/catalog/docker/vufind.sql:/docker-entrypoint-initdb.d/101_vufind.sql
      - ${BABEL_HOME}/sql/auth.sql:/docker-entrypoint-initdb.d/102_auth.sql
      - ${BABEL_HOME}/sql/permissions.sql:/docker-entrypoint-initdb.d/201_permissions.sql
      - ${BABEL_HOME}/mb/etc/sql/999_mb.sql:/docker-entrypoint-initdb.d/999_mb.sql
      - mysql_sdr_data:/var/lib/mysql
    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: TIMTOWTDIBSCINABTE

#### INDEXING

  # We add the 'indexing' profile to keep these from starting automatically
  # when we do 'docker-compose up'

  slip:
    build: ./slip
    image: hathitrust-slip
    user: ${CURRENT_USER}
    volumes:
      - ${BABEL_HOME}:/htapps/babel
      # this is where docs-j saves output
      - ${BABEL_HOME}/slip/sample:/htapps/babel/logs/tmp
      - ${BABEL_HOME}/sample-data/sdr1:/sdr1
      - ${BABEL_HOME}/sample-data/etc:/htapps/babel/etc
      - ${BABEL_HOME}/sample-data:/tmp/sample-data
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
      - HT_DEV=docker
    depends_on:
      - mysql-sdr
      - solr-sdr-catalog
      - solr-lss-dev
    command: bash
    profiles:
      - indexing

  traject:
    build: ./hathitrust_catalog_indexer
    environment:
      - SOLR_URL=http://solr-sdr-catalog:9033/solr/catalog
      - redirect_file=/dev/null
      - NO_DB=1
      - DDIR=/app/metadata
    depends_on:
      - solr-sdr-catalog
    volumes:
      - ${BABEL_HOME}/sample-data/metadata:/app/metadata
      - ${BABEL_HOME}/hathitrust_catalog_indexer:/app
      - gem_cache:/gems
    profiles:
      - indexing

  stage-item:
    build: ./stage-item
    # no explicit depends-on - the stage item script will start catalog, traject, etc as needed
    volumes:
      - ${BABEL_HOME}:/usr/src/babel
      - gem_cache:/gems
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql-sdr
    environment:
      - CATALOG_SOLR=http://solr-sdr-catalog:9033/solr/catalog
      - LSS_SOLR=http://solr-lss-dev:8983/solr/core-x
      - MYSQL_URL=mysql2://mdp-admin:mdp-admin@mysql-sdr:3306/ht
    profiles:
      - stage_item

  # todo: ingest, bound to sample-data

volumes:
  gem_cache:
  mysql_sdr_data:
  solr_sdr_catalog:
