include:
  - common/docker/core.yml

services:
  # Fontend Services
  playwright:
    extends:
      file: common/docker/playwright.yml
      service: playwright
    depends_on:
      apache:
        condition: service_healthy
    profiles:
      - playwright_testing

  playwright_reports:
    extends:
      file: common/docker/playwright.yml
      service: playwright
    command: "npx playwright show-report --host 0.0.0.0"
    ports:
      - 9323:9323
    profiles:
      - playwright_testing

  firebird:
    extends:
      file: common/docker/node.yml
      service: firebird
    profiles:
      - frontend
  page-turner:
    extends:
      file: common/docker/node.yml
      service: page-turner
    profiles:
      - frontend

  storybook:
    extends:
      file: common/docker/node.yml
      service: page-turner
    command: npm run storybook -- --host 0.0.0.0
    ports:
      - "6006:6006"
    profiles:
      - storybook

# Backend Services
  apache:
    extends:
      file: common/docker/apache.yml
      service: apache
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
      imgsrv:
        condition: service_healthy
    ports:
      - "8080:8080"
    profiles:
      - backend
      - playwright_testing

  perl-test:
    extends:
      file: common/docker/perl.yml
      service: perl
    command: "prove -r imgsrv/t ls/t mdp-lib/t"
    profiles:
      - testing

  perl-dev:
    extends:
      file: common/docker/perl.yml
      service: perl
    # This environment is provided by perl.yml so should not be needed here
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
    command: "/bin/bash"
    profiles:
      - backend

# Optional dependencies; not included in current playwright testing
  vufind:
    extends:
      file: common/docker/catalog.yml
      service: vufind
    profiles:
      - backend

  composer:
    build: catalog
    volumes:
      - ${BABEL_HOME}/catalog:/app
    working_dir: /app
    command: composer install

  solr-lss-dev:
    extends:
      file: common/docker/solr.yml
      service: solr-lss-dev
    profiles:
      - backend
      - stage_item

  solr-ptsearch:
    extends:
      file: common/docker/solr.yml
      service: solr-ptsearch
    profiles:
      - backend

# Indexing
  traject:
    extends:
      file: common/docker/stage-item.yml
      service: traject
    depends_on:
      solr-sdr-catalog:
        condition: service_healthy
    profiles:
    - indexing
    - stage_item

  stage-item:
    extends:
      file: common/docker/stage-item.yml
      service: stage-item
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-lss-dev:
        condition: service_healthy
    profiles:
    - stage_item

  slip:
    extends:
      file: common/docker/stage-item.yml
      service: slip
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
      solr-lss-dev:
        condition: service_healthy
    profiles:
    - indexing
    - stage_item

volumes:
  gem_cache:
