version: '3'

services:

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ../catalog:/app
      - ../common:/app/common-dev
    depends_on:
      - vufind
      - imgsrv

  apache-cgi:
    build:
      context: ".."
      dockerfile: "./babel-local-dev/Dockerfile"
    volumes:
      - ../catalog:/htapps/app
      - ../common:/htapps/babel/common
      - ../imgsrv:/htapps/babel/imgsrv
      - ../pt:/htapps/babel/pt
      - ../mdp-web:/htapps/babel/mdp-web
      - ../mdp-lib:/htapps/babel/mdp-lib
      - ../slip-lib:/htapps/babel/slip-lib
      - ../plack-lib:/htapps/babel/plack-lib
      - "../imgsrv-sample-data/sdr1:/sdr1"
      - "../imgsrv-sample-data/etc:/htapps/babel/etc"
      - "../imgsrv-sample-data/watermarks:/htapps/babel/watermarks"
      - "../imgsrv-sample-data:/tmp/imgsrv-sample-data"
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
      - HT_DEV=
      - MARIADB_USER=ht_web
      - REMOTE_ADDR=127.0.0.1
      - HTTP_HOST=127.0.0.1
    depends_on:
      - mysql-sdr
      - solr-sdr-catalog
    ports:
      - "41028:41028"

  # assumes imgsrv-sample-data has been checked out next to "imgsrv"
  imgsrv:
    build: ../imgsrv
    volumes:
      - ../imgsrv:/htapps/babel/imgsrv
      - "../imgsrv-sample-data/sdr1:/sdr1"
      - "../imgsrv-sample-data/etc:/htapps/babel/etc"
      - "../imgsrv-sample-data/watermarks:/htapps/babel/watermarks"
      - "../imgsrv-sample-data:/tmp/imgsrv-sample-data"
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
      - HT_DEV=
      - MARIADB_USER=ht_web
      - REMOTE_ADDR=127.0.0.1
      - HTTP_HOST=127.0.0.1
    depends_on:
      - mysql-sdr
      - solr-sdr-catalog
    ports:
      - "31028:31028"
    command: bash -c "/htapps/babel/imgsrv/bin/startup_imgsrv"

  solr-sdr-catalog:
    image: ghcr.io/hathitrust/catalog-solr-sample
    ports:
      - "9033:9033"

  mysql-sdr:
    image: mariadb
    volumes:
      - ../catalog/docker/vufind.sql:/docker-entrypoint-initdb.d/vufind.sql
      - ../imgsrv/vendor/common-lib/lib/sql/000_ht_schema.sql:/docker-entrypoint-initdb.d/0000_ht_schema.sql
      - ../imgsrv/vendor/common-lib/lib/sql/001_ht_ht_namespaces.sql:/docker-entrypoint-initdb.d/001_ht_ht_namespaces.sql
      - ../imgsrv/vendor/common-lib/lib/sql/002_ht_rights_current.sql:/docker-entrypoint-initdb.d/002_ht_rights_current.sql
      - ../imgsrv/sql/100_ht_web_schema.sql:/docker-entrypoint-initdb.d/100_ht_web_schema.sql
      - ../imgsrv/sql/200_users.sql:/docker-entrypoint-initdb.d/200_users.sql

    environment:
      # - MARIADB_RANDOM_ROOT_PASSWORD=1
      MYSQL_ROOT_PASSWORD: TIMTOWTDIBSCINABTE

  vufind:
    build: ../catalog
    hostname: 'catalog-dev'
    volumes:
      - ../catalog:/app
    depends_on:
      - mysql-sdr
      - solr-sdr-catalog

volumes:
  # sdr1:
  data_db:
