include:
  - common/docker/core.yml

services:
  # Fontend Services
  playwright:
    extends:
      file: common/docker/playwright.yml
      service: playwright
    depends_on:
      apache-test:
        condition: service_healthy
    profiles:
      - playwright_testing

  playwright_reports:
    extends:
      file: common/docker/playwright.yml
      service: playwright
    command: "npx playwright show-report --host 0.0.0.0"
    ports:
      - 9323:9323
    profiles:
      - playwright_testing


  firebird:
    extends:
      file: common/docker/node.yml
      service: firebird
    profiles:
      - frontend
  page-turner:
    extends:
      file: common/docker/node.yml
      service: page-turner
    profiles:
      - frontend

  apache-test:
    extends:
      file: common/docker/apache.yml
      service: apache
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
      imgsrv:
        condition: service_healthy

# Backend Services
  apache:
    extends:
      file: common/docker/apache.yml
      service: apache
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-lss-dev:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
      solr-ptsearch:
        condition: service_healthy
      imgsrv:
        condition: service_healthy
      vufind:
        condition: service_healthy
    ports:
      - "8080:8080"
    profiles:
      - backend

  perl-test:
    extends:
      file: common/docker/perl.yml
      service: perl
    command: "prove -r imgsrv/t mdp-lib/t"
    profiles:
      - testing

  perl-dev:
    extends:
      file: common/docker/perl.yml
      service: perl
    # This environment is provided by perl.yml so should not be needed here
    environment:
      - SDRROOT=/htapps/babel
      - SDRDATAROOT=/sdr1
    command: "/bin/bash"
    profiles:
      - backend

# Indexing
  traject:
    extends:
      file: common/docker/stage-item.yml
      service: traject
    depends_on:
      solr-sdr-catalog:
        condition: service_healthy
    profiles:
    - indexing
    - stage_item

  stage-item:
    extends:
      file: common/docker/stage-item.yml
      service: stage-item
    depends_on:
      mysql-sdr:
        condition: service_healthy
    profiles:
    - stage_item

  slip:
    extends:
      file: common/docker/stage-item.yml
      service: slip
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
      solr-lss-dev:
        condition: service_healthy
    profiles:
    - indexing
    - stage_item

volumes:
  gem_cache:
