#!/l/local/bin/perl

=head1 NAME

access_stmts

=head1 USAGE

http://babel.hathitrust.org/mdp-misc/cgi/access_stmts

=head1 DESCRIPTION

Dump of access_stmts and access_map 

=head1 VERSION

=head1 OPTIONS

=over 8

=item URL params

Debug options

=back

=cut

# ----------------------------------------------------------------------
# Set up paths for local libraries -- must come first
# ----------------------------------------------------------------------
use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors;

#
# Establish and populate the Context.  Order dependent.
#
# Perl
use CGI qw/:standard/;
use Date::Calc;

# App
use Utils;
use Utils::Time;
use Context;
use MdpConfig;
use Database;

# ============================ Main ===================================

my $uber_configfile = Utils::get_uber_config_path('mdp-misc');
my $config = new MdpConfig($uber_configfile);
my $db = new Database($config);
my $DBH = $db->get_DBH();

my $cgi = new CGI;

my $date = `date`;

print header(-charset => 'utf-8');
print start_html(-title=>"Hathitrust access statements and map",
                 -head=>[],
                );
print div({-class=>"brandingLogo"},
          a({-href=>"http://hathitrust.org"},
            img({-src=>"/ht-graphics/web/HathiTrustDL_logo.png", -style=>"border:0"})));
print div("Digital Library - access statements and map - $date");

my @rows;

my $ref_to_ary_of_hashref = get_stmts();
foreach my $hashref (@$ref_to_ary_of_hashref) {
    my $key = $hashref->{'stmt_key'};
    my $url = $hashref->{'stmt_url'};
    my $head = $hashref->{'stmt_head'};
    my $text = $hashref->{'stmt_text'};

    push(@rows, Tr(td([$key]) . td([$url]) . td([$head]) . td([$text])));
}

my $table = table({-border=>"1", -width=>"100%", -cellpadding=>"5px", -cellspacing=>0},
                  @rows);

print $table;

print end_html();


exit 0;

# ---------------------------------------------------------------------

=item get_stmts

Description

=cut

# ---------------------------------------------------------------------
sub get_stmts {
    my $statement = qq{SELECT stmt_key, stmt_url, stmt_head, stmt_text FROM access_stmts};
    my $sth = DbUtils::prep_n_execute($DBH, $statement);
    my $ref_to_ary_of_hashref = $sth->fetchall_arrayref({});

    return $ref_to_ary_of_hashref;
}


=head1 AUTHOR

Phillip Farber, University of Michigan, pfarber@umich.edu

=head1 COPYRIGHT

Copyright 2010 ©, The Regents of The University of Michigan, All Rights Reserved

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject
to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

=cut
