#!/l/local/bin/perl

=head1 NAME

access_stmts_api

=head1 USAGE

http://babel.hathitrust.org/mdp-misc/cgi/access_stmts_api?attr=1;src=3;fields=stmt_key,stmt_url

=head1 DESCRIPTION

API to retrieve access statements and associated data

=head1 OPTIONS

=over 8

=item URL params

none or {attr,src}

=back

=head1 METHODS

=back

=cut

use strict;

# ----------------------------------------------------------------------
# Set up paths for local libraries -- must come first
# ----------------------------------------------------------------------
use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors;

#
# Establish and populate the Context.  Order dependent.
#
# Perl
use CGI qw/:standard/;

# App
use Utils;
use Context;
use MdpConfig;
use Database;
use Access::Statements;
use RightsGlobals;


# ============================ Main ===================================

my $C = new Context;

my $uber_configfile = Utils::get_uber_config_path('mdp-misc');
my $config = new MdpConfig($uber_configfile);
my $db = new Database($config);
$C->set_object('Database', $db);

my $cgi = new CGI;

my $attr = $cgi->param('attr');
my $source = $cgi->param('src');
my $fields = $cgi->param('fields');
my @fields = split(/,/, $fields);

my $output_buffer = '';
if ($attr && $source) {
    $output_buffer = fetch_output_data($attr, $source, \@fields);
}

my $status;
if ($output_buffer) {
    $status = '200 OK';
}
else {
    $status = '400 BAD REQUEST Invalid URI';
}


print header(
             -Status => $status,
             -Content_type => 'application/xml',
             -charset => 'utf-8',
            );

print $output_buffer;

exit 0;

# ---------------------------------------------------------------------

=item __build_xml

Description

=cut

# ---------------------------------------------------------------------
sub __build_xml {
    my $hashref = shift;

    my $buf .= '<AccessFields>';
    
    my $key = $hashref->{stmt_key};
    if ($key) {
        $buf .= wrap_string_in_tag($key, 'Key');
    }
    my $url = $hashref->{stmt_url};
    if ($url) {
        $buf .= wrap_string_in_tag($url, 'Url');
    }
    my $aux_url = $hashref->{stmt_url_aux};
    if ($aux_url) {
        $buf .= wrap_string_in_tag($key, 'AuxUrl');
    }
    my $head = $hashref->{stmt_head};
    if ($head) {
        $buf .= wrap_string_in_tag($head, 'Head');
    }
    my $icon = $hashref->{stmt_icon};
    if ($icon) {
        $buf .= wrap_string_in_tag($icon, 'Icon');
    }
    my $aux_icon = $hashref->{stmt_icon_aux};
    if ($aux_icon) {
        $buf .= wrap_string_in_tag($aux_icon, 'AuxIcon');
    }
    my $text = $hashref->{stmt_text};
    if ($text) {
        $buf .= wrap_string_in_tag($text, 'Text');
    }

    $buf .= '</AccessFields>';    
}

# ---------------------------------------------------------------------

=item fetch_output_data

Description

=cut

# ---------------------------------------------------------------------
sub fetch_output_data {
    my ($attr, $source, $fields_arr_ref) = @_;

    my %h = map { $_ => 1 } @$fields_arr_ref;

    my $ref_to_arr_of_hashref =
      Access::Statements::get_stmt_by_rights_values($C, undef, $attr, $source, \%h);
    
    my $buf;
    foreach my $hashref (@$ref_to_arr_of_hashref) {
        $buf .= __build_xml($hashref);
    }

    return $buf;
}



=head1 AUTHOR

Phillip Farber, University of Michigan, pfarber@umich.edu

=head1 COPYRIGHT

Copyright 2011 ©, The Regents of The University of Michigan, All Rights Reserved

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject
to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

=cut
