#!/l/local/bin/perl

=head1 NAME

CB-update-rights

=head1 USAGE

/htapps/babel/mb/scripts/CB-update-rights

=head1 DESCRIPTION

Update mdp.o_item.rights from mdp.rights_current.namespace,id

=head1 OPTIONS

=over 8

=item -n

Debug options

=back

=cut

use strict;
use Getopt::Std;

my $INTERACTIVE = $ENV{TERM};

our ($opt_e);

my $ops = getopts('e');
my $EMAIL = $opt_e;

# ----------------------------------------------------------------------
# Set up paths for local libraries -- must come first
# ----------------------------------------------------------------------
use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors;

use Utils;
use Context;
use Database;
use MdpConfig;
use Debug::DUtils;
use Collection;
use Identifier;
use Mail::Mailer;
use MetadataQueue;
use MBooks::MetaDataGetter;

#
# Establish and populate the Context.  Order dependent.
#
my $C = new Context;
my $CONFIG = new MdpConfig(
                           Utils::get_uber_config_path('mb'),
                           $ENV{SDRROOT} . "/mb/lib/Config/global.conf",
                           $ENV{SDRROOT} . "/mb/lib/Config/local.conf"
                          );
$C->set_object('MdpConfig', $CONFIG);
# Database connection
my $db = new Database($C->get_object('MdpConfig'));
my $DBH = $db->get_DBH($C);
$C->set_object('Database', $db);


my $CO = new Collection($DBH, $CONFIG, 'no_owner');
$C->set_object('Collection', $CO);

CB_delete_extras($C);
CB_do_update_metadata($C);

email_report()
  if ($EMAIL);


exit 0;

# ---------------------------------------------------------------------

=item __P

Description

=cut

# ---------------------------------------------------------------------
my $EMAIL_BUFFER = '';

sub __P {
    my $msg = shift;

    $EMAIL_BUFFER .= $msg;
    
    return if (! $ENV{'TERM'});
    print STDOUT qq{$msg};
}

# ---------------------------------------------------------------------

=item email_report

Description

=cut

# ---------------------------------------------------------------------
sub email_report {
    my $g_assert_email_to_addr   = q{pfarber@umich.edu,tburtonw@umich.edu};
    my $g_assert_email_from_addr = q{"Collection Builder Mailer" <dlps-help@umich.edu>};

    my $when = Utils::Time::iso_Time();
    my $email_subject = qq{[CB] Metadata update ($when)};

    my $mailer = new Mail::Mailer('sendmail');
    $mailer->open({
                   'To'      => $g_assert_email_to_addr,
                   'From'    => $g_assert_email_from_addr,
                   'Subject' => $email_subject,
                  });
    print $mailer($EMAIL_BUFFER);
    $mailer->close;
}


# ---------------------------------------------------------------------

=item CB_delete_extras

Description

=cut

# ---------------------------------------------------------------------
sub CB_delete_extras {
    my($C) = @_;

    my $size = 100;
    
    my ($statement, $sth);

    my $num_o_item = 0;
    my $num_deleted_from_o_item = 0;

    __P(qq{delete extras:\n});

    while (1) {
        $statement = qq{LOCK TABLES o_item WRITE, o_coll_item WRITE};
        $sth = DbUtils::prep_n_execute($DBH, $statement);

        # One hundred at a time so we don't race/block with Collection Builder users
        $statement = 
          qq{SELECT extern_item_id FROM o_item WHERE extern_item_id NOT IN (SELECT DISTINCT extern_item_id FROM o_coll_item) LIMIT $size};
        $sth = DbUtils::prep_n_execute($DBH, $statement);
        my $ref_to_arr_of_hashref = $sth->fetchall_arrayref({});

        my $num = (scalar @$ref_to_arr_of_hashref);
        if (! $num) {
            $statement = qq{UNLOCK TABLES};
            $sth = DbUtils::prep_n_execute($DBH, $statement);
            last;
        }
        
        foreach my $hashref (@$ref_to_arr_of_hashref) {
            $num_o_item++;
            my $extern_item_id = $hashref->{extern_item_id};

            __P( qq{A: o_item not in o_coll_item: $extern_item_id\n});
            $statement = qq{DELETE FROM o_item WHERE extern_item_id='$extern_item_id'};
            $sth = DbUtils::prep_n_execute($DBH, $statement);
                
            $num_deleted_from_o_item++;
        }

        $statement = qq{UNLOCK TABLES};
        $sth = DbUtils::prep_n_execute($DBH, $statement);
    }

    __P(qq{num o_item not in o_coll_item=$num_o_item\n});
    __P(qq{num deleted in o_item=$num_deleted_from_o_item\n});
}

# ---------------------------------------------------------------------

=item Name 

Description

=cut

# ---------------------------------------------------------------------
sub __cb_get_metadata_hashref {
    my $C = shift;
    my $id = shift;

    my $mdg = new MBooks::MetaDataGetter($C, [$id]);
    my $metadata_aryref = $mdg->metadata_getter_get_metadata($C, [$id]);

    if ($metadata_aryref) {
        my $metadata_hashref = $metadata_aryref->[0];
        $metadata_hashref = $mdg->normalize_metadata($metadata_hashref);
        
        return $metadata_hashref;
    }
    else {
        __P( qq{Could not get metadata for id="$id"} );
        return undef;
    }
}


# ---------------------------------------------------------------------

=item __cb_update_metadata

Description

=cut

# ---------------------------------------------------------------------
sub __cb_update_metadata {
    my $id = shift;
    my $metadata_hashref = shift;

    eval {
        $CO->create_or_update_item_metadata($metadata_hashref);
    };
    if ($@) {
        __P( qq{Could not update id="$id": $@} );

        return 0;
    }

    return 1;
}

# ---------------------------------------------------------------------

=item CB_do_update_metadata

Description

=cut

# ---------------------------------------------------------------------
sub CB_do_update_metadata {
    my($C) = @_;

    __P(qq{update metadata:\n});

    my $queue_error = 0;
    
    my $num_updated = 0;
    my $num_fetch_failed = 0;
    my $num_update_failed = 0;
    
    while (1) {
        my ($ok, $id) = MetadataQueue::get_next_metadata_item_id($C, $DBH);

        if ($ok) {
            if ($id) {
                next unless ($CO->item_exists($id));
                
                __P(qq{updating: $id\n});
        
                my $metadata_hashref = __cb_get_metadata_hashref($C, $id);
                my $fetch_ok = $metadata_hashref ? 1 : 0;
         
                if ($fetch_ok) {
                    my $update_ok = __cb_update_metadata($id, $metadata_hashref);
                    if ($update_ok) {
                        $num_updated++;
                        MetadataQueue::dequeue_id_from_metadata_queue($C, $DBH, $id);
                    }
                    else {
                        # Leave the ID in the queue
                        $num_update_failed++;
                    }
                }
                else {
                    # Leave the ID in the queue
                    $num_fetch_failed++;
                }
            }
            else {
                last;
            }
        }
        else {
            $queue_error = 1;
            last;
        }
    }
    __P(qq{Report: num_updated=$num_updated\n\tqueue_error=$queue_error num_fetch_failed=$num_fetch_failed num_update_failed=$num_update_failed\n});
}



exit 0;




=head1 AUTHOR

Phillip Farber, University of Michigan, pfarber@umich.edu

=head1 COPYRIGHT

Copyright 2011 ©, The Regents of The University of Michigan, All Rights Reserved

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject
to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

=cut
