#!/usr/bin/env perl

use CGI;

#XXX WARNING: this map no longer in use.  
my $LS_MAP = {
    all => 'ocr',
    title => 'title',
    author => 'author',
    subject => 'subject',
    isbn => 'isn',
    publisher => 'publisher',
    seriestitle => 'series',
    ocronly =>'ocronly',
    pubyear => ''
};


#XXX currently ls does not allow searching by publication year only limiting by
# solr query would search for publishDate:query
#   redo solr? or kludge?

my $cgi = new CGI;
my $base = $cgi->url(-full => 1);

my $target = $cgi->param('target');
my $searchtype = $cgi->param('searchtype');
my $q1 = $cgi->param('q1');
my $ft = $cgi->param('ft');
my $dest_cgi = new CGI({});
my $dest_url; my $dest_base;

my $LS_DOMAIN = qq{babel.hathitrust.org};
my $CATALOG_DOMAIN = qq{catalog.hathitrust.org};

my $LS_SCHEME = qq{http};
if ( $cgi->https() ) {
    $LS_SCHEME = qq{https};
}

my $referer = $cgi->referer();
if ( ( $referer =~ m,/test\., && $referer !~ m,\.babel, ) || $referer =~ m,/beta-3, ) {
    # referer is a dev instance; update links
    $LS_DOMAIN = qq{test.$LS_DOMAIN};
    $CATALOG_DOMAIN = qq{test.$CATALOG_DOMAIN};
} elsif ( $referer =~ m,/(.*)\.babel, ) {
    # referer is a babel dev instance
    $LS_DOMAIN = $ENV{SERVER_NAME};
    $CATALOG_DOMAIN = qq{test.$CATALOG_DOMAIN};
} elsif ( my ( $prefix ) = $referer =~ m,https?://(.*)\.catalog., ) {
    # referer is a catalog dev instance
    $CATALOG_DOMAIN = qq{$prefix.$CATALOG_DOMAIN};
}
# still needs to handle case of a catalog dev server

my $LS_URL = qq{$LS_SCHEME://$LS_DOMAIN/cgi/ls};
my $CATALOG_URL = qq{http://$CATALOG_DOMAIN/Search/Home};

if ( $target eq 'ls' ) {
#  XXX hardcode debug env for now  $dest_base = qq{http://babel.hathitrust.org/cgi/ls};
    # $dest_base = qq{http://tburtonw-full.babel.hathitrust.org/cgi/ls};
    $dest_base = $LS_URL;
    #   no field types for ls, just the default everything "ocr" search
    #    $dest_cgi->param('field1', $$LS_MAP{$searchtype});
    $dest_cgi->param('field1', 'ocr');
    $dest_cgi->param('q1', $q1);
    $dest_cgi->param('a', 'srchls');
    if ($ft eq "ft")
    {
        $dest_cgi->param('lmt', 'ft');
    }
    
} else {
  # $dest_base = qq{http://dueberb.catalog.hathitrust.org/Search/Home};
    $dest_base = $CATALOG_URL;
    $dest_cgi->param('lookfor', $q1);
    $dest_cgi->param('searchtype', $searchtype);
    if ($ft eq "ft")
    {
        $dest_cgi->param('ft', 'ft');
        $dest_cgi->param('setft', 'true');
    }
    else 
    {
        $dest_cgi->param('ft', '');
        $dest_cgi->param('setft', 'false');
    }

}

my $dest_url = $dest_cgi->url(-full=>1, -query=>1);
$dest_url =~ s,$base,$dest_base,;
if ( $target eq 'catalog' ) {
    $dest_url =~ s,;,&,g;
}

if ( $cgi->param('debug') ) {
    print $cgi->header('text/plain');
    print "TARGET = $target\n";
    print $dest_url, "\n";
    print $cgi->url(-full=>1, -query=>1);
} else {
    print $cgi->redirect($dest_url);
}
