#!/usr/bin/env perl

use warnings;
use strict;

use Getopt::Std;

use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors;

use CGI;

use Context;
use Database;
use Utils;
use DbUtils;
use MdpConfig;

use KGS_Log;
# make sure cache files/dirs are group writable
umask 0002;

# MDP stuff
my $C = new Context;

# configuration
my $config = new MdpConfig(
                           Utils::get_uber_config_path('kgs'),
                           $ENV{SDRROOT} . "/kgs/lib/Config/global.conf",
                           $ENV{SDRROOT} . "/kgs/lib/Config/local.conf"
                          );
$C->set_object('MdpConfig', $config);

# Database connection
my $db = new Database($config);
my $dbh = $db->get_DBH();


# ---------------------------------------------------------------------

=item __get_usage

Description

=cut

# ---------------------------------------------------------------------
sub __get_usage {
    my $s = qq{Usage: delete-kgs-account [ -e email | -u userid ]\n};
    return $s;
}

our ($opt_e, $opt_u);

my $ops = getopts('e:u:');

my ($EMAIL, $USERID);

if (defined $opt_e) {
    $EMAIL = $opt_e;
}
elsif (defined $opt_u) {
    $USERID = $opt_u;
}
else {
    print __get_usage();
    exit 0;
}

my $access_key = '';
my ($statement, $sth, $s);

if ($EMAIL) {
    $statement = qq{SELECT access_key FROM da_authentication WHERE email=?};
    $sth = DbUtils::prep_n_execute($dbh, $statement, $EMAIL);
    $access_key = $sth->fetchrow_array();
    $s = qq{Deleting account using email="$EMAIL"}
}
elsif ($USERID) {
    $statement = qq{SELECT access_key FROM da_authentication WHERE userid=?};
    $sth = DbUtils::prep_n_execute($dbh, $statement, $USERID);
    $access_key = $sth->fetchrow_array();
    $s = qq{Deleting account using userid="$USERID"}
}
else {
    die "Program error\n";
}

if (! $access_key) {
    print qq{Could not retrieve access_key.\n};
    exit 0;
}


print "$s with access_key=$access_key\n";
LOG($C, $s);

print "Clean da_authentication\n";
$statement = qq{DELETE FROM da_authentication WHERE access_key=?};
$sth = DbUtils::prep_n_execute($dbh, $statement, $access_key);

print "Clean da_authorization\n";
$statement = qq{DELETE FROM da_authorization WHERE access_key=?};
$sth = DbUtils::prep_n_execute($dbh, $statement, $access_key);

print "Clean da_requests\n";
$statement = qq{DELETE FROM da_requests WHERE access_key=?};
$sth = DbUtils::prep_n_execute($dbh, $statement, $access_key);

print "Clean da_statistics\n";
$statement = qq{DELETE FROM da_statistics WHERE access_key=?};
$sth = DbUtils::prep_n_execute($dbh, $statement, $access_key);

print "Clean da_rates\n";
$statement = qq{DELETE FROM da_rates WHERE access_key=?};
$sth = DbUtils::prep_n_execute($dbh, $statement, $access_key);

exit 0;




    
    




