#!/usr/bin/env perl 

use strict;
use warnings;

umask 0000;

use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors;

use CGI;
use OAuth::Lite::ServerUtil;

use API::HTD_Log;

# Shared with sample dapiclient
my $secret_key = 'PUBLIC_OAUTH_CONSUMER_SECRET';

my $cgi = new CGI;

my $util = OAuth::Lite::ServerUtil->new;
$util->support_signature_method('HMAC-SHA1');
$util->allow_extra_params(qw/hello/);

my $oauth_params = $cgi->Vars();
my $request_uri = $cgi->self_url;

hLOG(qq{dapiserver: request url=$request_uri});

unless ($util->validate_params($oauth_params)) {
    print $cgi->header(-Status => '400 ' . $util->errstr);
    exit 1;
}

unless ($util->verify_signature
        (
         method          => 'GET',
         params          => $oauth_params,
         url             => $request_uri,
         consumer_secret => $secret_key,
        )) {
    print $cgi->header(-Status => '401 ' . $util->errstr);
    exit 1;
}

print $cgi->header(-Status => '200 OK');
print qq{<div style="color: blue;"><b>[SERVER] received client request. Using secret=$secret_key<br/>echoing request parameters:</b>};
print $cgi->as_string();
print '</div>';

exit 0;
