#!/usr/bin/env perl 

=head1 NAME

dapiclient

=head1 DESCRIPTION

This is an example perl 2-legged oauth client that shares the secret
key "PUBLIC_OAUTH_CONSUMER_SECRET" with the HathiTrust sample server
called dapiserver.  It is intended to aid development of a fully
function Data API client in Perl or other languages that implement
HMAC_SHA1 OAuth libraries.

=head1 SYNOPSIS

For example:

http://yourhost.edu/path/to/client/dapiclient

=head1 OUTPUT

 [CLIENT] sent this URL to server:
 
   http://yourhost.edu/path/to/client/dapiserver?hello=world&oauth_consumer_key=PUBLIC_OAUTH_CONSUMER_KEY&oauth_nonce=47b8186be439110b4f98&oauth_signature=2cQYAM%2BYek%2BiOexZKMObM%2B3B2w4%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1332184191&oauth_version=1.0
 
 [CLIENT] received this HTTP response from server:
   200 OK

 [CLIENT] received this content response from server:

    [SERVER] received client request. echoing request parameters:

    hello
      world    
    oauth_consumer_key
      PUBLIC_OAUTH_CONSUMER_KEY
    oauth_nonce
      47b8186be439110b4f98
    oauth_signature
      2cQYAM+Yek+iOexZKMObM+3B2w4=
    oauth_signature_method
      HMAC-SHA1
    oauth_timestamp
      1332184191
    oauth_version
      1.0

=cut

use strict;
use warnings;

use CGI;
use OAuth::Lite::Consumer;
use OAuth::Lite::AuthMethod;


my $access_key = 'PUBLIC_OAUTH_CONSUMER_KEY';
my $secret_key = 'PUBLIC_OAUTH_CONSUMER_SECRET';

my $request_url = 'http://babel.hathitrust.org/cgi/htdc/dapiserver';

my $consumer = OAuth::Lite::Consumer->new
  (
   consumer_key    => $access_key,
   consumer_secret => $secret_key,
   auth_method     => OAuth::Lite::AuthMethod::URL_QUERY,
  );

my $response = $consumer->request
  (
   method  => 'GET',
   url     => $request_url,
   params  => {
               'hello' => 'world',
              },
  );

print CGI::header();

print "<p><b>[CLIENT] sent this URL to server using secret=$secret_key :</b><br/>";
print $consumer->oauth_request->uri;

print "<p><b>[CLIENT] received this HTTP response from server:</b><br/>";
print $response->status_line;
if ($response->is_success) {
    print "<br/><b>[CLIENT] received this content response from server:</b><blockquote>" . $response->content . "</blockquote>";
}

exit 0;
