services:
  apache:
    # Used for serving everything. A core service as well.
    build:
      context: .
      target: apache
    user: ${CURRENT_USER}
    volumes:
    - ${BABEL_HOME}:/htapps/babel
    - ${BABEL_HOME}/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    - ${BABEL_HOME}/apache/auth:/etc/apache2/auth
    - ${BABEL_HOME}/sample-data/sdr1:/sdr1
    - ${BABEL_HOME}/sample-data/etc:/htapps/babel/etc
    - ${BABEL_HOME}/sample-data:/tmp/sample-data
    - ${BABEL_HOME}/catalog:/htapps/catalog
    - ${BABEL_HOME}/mb/lib/Config/docker-local.conf:/htapps/babel/mb/lib/Config/local.conf
    - ${BABEL_HOME}/ls/lib/Config/docker-local.conf:/htapps/babel/ls/lib/Config/local.conf
    - ${BABEL_HOME}/logs:/var/log/babel
    environment:
    - SDRROOT=/htapps/babel
    - SDRDATAROOT=/sdr1
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-lss-dev:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
      solr-ptsearch:
        condition: service_healthy
      imgsrv:
        condition: service_healthy
      vufind:
        condition: service_healthy
    ports:
    - "8080:8080"
    healthcheck:
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 5
      test: "curl -f --retry-connrefused http://localhost:8080/"
