x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:
  solr-sdr-catalog:
    # This is a core service
    image: ghcr.io/hathitrust/catalog-solr-sample
    ports:
    - "9033:9033"
    volumes:
    - solr_sdr_catalog:/var/solr
    healthcheck:
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 5
      test: "curl -f --retry-connrefused http://localhost:9033"

  solr-lss-dev:
    # This is another core service
    image: solr:6.6.6-alpine
    ports:
    - "8983:8983"
    user: ${CURRENT_USER}
    volumes:
    - ${BABEL_HOME}/lss_solr_configs/solr6_standalone/lss-dev/core-x:/opt/solr/server/solr/core-x
    - ${BABEL_HOME}/lss_solr_configs/solr6_standalone/lss-dev/core-y:/opt/solr/server/solr/core-y
    - ${BABEL_HOME}/lss_solr_configs/solr6_standalone:/opt/lss_solr_configs
    - ${BABEL_HOME}/lss_solr_configs/solr6_standalone/lib:/opt/solr/server/solr/lib
    - ${BABEL_HOME}/logs/solr:/opt/solr/server/logs
    healthcheck:
      <<: *healthcheck-defaults
      test: "ping -c 1 solr-lss-dev:8983"

  solr-ptsearch:
    # This is a core service
    build: ../../ptsearch-solr #TODO: Build from image in ghcr.io
    ports:
    - "8984:8983"
    healthcheck:
      <<: *healthcheck-defaults
      test: "curl -f --retry-connrefused http://solr-ptsearch:8983/solr/ptsearch/admin/ping"

  mysql-sdr:
    # This is a core service
    image: ghcr.io/hathitrust/db-image:latest
    volumes:
    - ${BABEL_HOME}/slip/etc/sql/100_slip.sql:/docker-entrypoint-initdb.d/100_slip.sql
    - ${BABEL_HOME}/sql/permissions.sql:/docker-entrypoint-initdb.d/201_permissions.sql
    - ${BABEL_HOME}/sql/auth.sql:/docker-entrypoint-initdb.d/202_auth.sql
    - ${BABEL_HOME}/mb/etc/sql/999_mb.sql:/docker-entrypoint-initdb.d/999_mb.sql
    - ${BABEL_HOME}/sql/vufind_session.sql:/docker-entrypoint-initdb.d/888_vufind.sql
    - mysql_sdr_data:/var/lib/mysql
    ports:
    - "3307:3306"
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  imgsrv:
    # This a core dependency
    build:
      context: ../../
      target: imgsrv-fcgi
    user: ${CURRENT_USER}
    volumes:
    - ${BABEL_HOME}:/htapps/babel
    - ${BABEL_HOME}/sample-data/sdr1:/sdr1
    - ${BABEL_HOME}/sample-data/etc:/htapps/babel/etc
    - ${BABEL_HOME}/sample-data/watermarks:/htapps/babel/watermarks
    - ${BABEL_HOME}/sample-data:/tmp/sample-data
    - ${BABEL_HOME}/logs:/var/log/babel
    environment:
    - SDRROOT=/htapps/babel
    - SDRDATAROOT=/sdr1
    - HT_DEV=docker
    - REMOTE_ADDR=127.0.0.1
    - HTTP_HOST=127.0.0.1
    - APACHE_LOG_DIR=/tmp
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
    ports:
    - "31028:31028"
    command: bash -c "/htapps/babel/imgsrv/bin/startup_imgsrv"
    healthcheck:
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 5
      test: "cgi-fcgi -bind -connect 127.0.0.1:31028"

  vufind:
    # A core service
    build: ../../catalog #TODO: Use the built unstable container
    hostname: 'catalog-dev'
    volumes:
    - ${BABEL_HOME}/catalog:/app
    - ${BABEL_HOME}/firebird-common:/htapps/babel/firebird-common
    environment:
    - FIREBIRD_HOME=/htapps/babel/firebird-common
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
    healthcheck:
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 5
      test: "service php7.4-fpm status | grep running"

volumes:
  mysql_sdr_data:
  solr_sdr_catalog:
