services:
  slip:
    # This is a backend service. Full text indexing. Check in with lainete
    build: ../../slip
    image: hathitrust-slip
    user: ${CURRENT_USER}
    volumes:
    - ${BABEL_HOME}:/htapps/babel
    # this is where docs-j saves output
    - ${BABEL_HOME}/slip/sample:/htapps/babel/logs/tmp
    - ${BABEL_HOME}/sample-data/sdr1:/sdr1
    - ${BABEL_HOME}/sample-data/etc:/htapps/babel/etc
    - ${BABEL_HOME}/sample-data:/tmp/sample-data
    - ${BABEL_HOME}/logs:/var/log/babel
    environment:
    - SDRROOT=/htapps/babel
    - SDRDATAROOT=/sdr1
    - HT_DEV=docker
    depends_on:
      mysql-sdr:
        condition: service_healthy
      solr-sdr-catalog:
        condition: service_healthy
      solr-lss-dev:
        condition: service_healthy
    command: bash
    profiles:
    - indexing
