# Optional services (not required for core functionality testing)
# As we want to test these via playwright, they should move into core.yml

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:
  solr-lss-dev:
    # This is another core service
    image: solr:6.6.6-alpine
    ports:
    - "8983:8983"
    user: ${CURRENT_USER}
    volumes:
    - ${BABEL_HOME}/lss_solr_configs/solr6_standalone/lss-dev/core-x:/opt/solr/server/solr/core-x
    - ${BABEL_HOME}/lss_solr_configs/solr6_standalone/lss-dev/core-y:/opt/solr/server/solr/core-y
    - ${BABEL_HOME}/lss_solr_configs/solr6_standalone:/opt/lss_solr_configs
    - ${BABEL_HOME}/lss_solr_configs/solr6_standalone/lib:/opt/solr/server/solr/lib
    - ${BABEL_HOME}/logs/solr:/opt/solr/server/logs
    healthcheck:
      <<: *healthcheck-defaults
      test: "ping -c 1 solr-lss-dev:8983"

  solr-ptsearch:
    # This is a core service
    build: ../../ptsearch-solr #TODO: Build from image in ghcr.io
    ports:
    - "8984:8983"
    environment:
      SOLR_MODULES: analysis-extras
    command: solr-foreground --user-managed # Ensures Solr 10 starts in standalone mode, which is required for the way we are mounting cores and configs
    healthcheck:
      <<: *healthcheck-defaults
      test: "curl -f --retry-connrefused http://solr-ptsearch:8983/solr/ptsearch/admin/ping"
