# Optional services (not required for core functionality testing)
# As we want to test these via playwright, they should move into core.yml

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:
  solr-lss-dev:
    image: ghcr.io/hathitrust/full-text-search-cloud:shards-docker
    container_name: solr-lss-dev
    ports:
     - "8981:8983"
    environment:
      - ZK_HOST=zoo1:2181
      - SOLR_OPTS=-XX:-UseLargePages
    depends_on:
      zoo1:
        condition: service_healthy
    volumes:
      - solr1_data:/var/solr/data
    command: [ "sh", "-c", 'solr-foreground -c & sleep 150 && export SOLR_AUTHENTICATION_OPTS=-Dbasicauth=admin:solrRocks && solr create_collection -d /opt/solr/core-x -c core-x -shards 1 -replicationFactor 1 -p 8983 && wait' ]
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD-SHELL", "curl -s -u admin:solrRocks 'http://solr-lss-dev:8983/solr/admin/collections?action=CLUSTERSTATUS&collection=core-x' | grep -q '\"state\":\"active\"'" ]
      interval: 30s
      start_period: 30s
      timeout: 30s
      retries: 10
  zoo1: # Zookeeper run in standalone mode for development and testing purposes. In production, we would use a Zookeeper ensemble for high availability.
    image: zookeeper:3.8.0
    container_name: zoo1
    restart: "no"
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      JVMFLAGS: "-XX:-UseContainerSupport"
    volumes:
      - zoo1_data:/data
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "nc", "-z", "-w", "2", "localhost", "2181" ] # Check if ZooKeeper is listening on port 2181
      interval: 30s
      start_period: 30s
      timeout: 30s
      retries: 10
  solr-ptsearch:
    # This is a core service
    build: ../../ptsearch-solr #TODO: Build from image in ghcr.io
    ports:
    - "8984:8983"
    environment:
      SOLR_MODULES: analysis-extras
    command: solr-foreground --user-managed # Ensures Solr 10 starts in standalone mode, which is required for the way we are mounting cores and configs
    healthcheck:
      <<: *healthcheck-defaults
      test: "curl -f --retry-connrefused http://solr-ptsearch:8983/solr/ptsearch/admin/ping"
volumes:
    solr1_data: null
    zoo1_data: null