#!/usr/bin/env perl

use strict;
use warnings;

use Plack::Runner;

BEGIN {
    ## $ENV{DEBUG_LOCAL} = 1;
    $ENV{PLACK_ENV} = ( defined $ENV{HT_DEV} ) ? 'development' : 'production';
}

use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors __FILE__;

# ----------------------------------------------------------------------
# enable strict, only under development
# ----------------------------------------------------------------------
BEGIN {
  if ( $ENV{'DLPS_DEV'} ) {
    require "strict.pm";
    strict::import();

    # Set the SDRINST and SDRLIB environment variables in auth
    # system absence.
    require Auth::Surrogate;
    Auth::Surrogate::authorize('/mb/cgi');
  }
}

use Plack::Builder;
use Plack::Builder::Conditionals::Choke;

use Download::Builder;

use Utils::Settings;
my $settings = Utils::Settings::load('mb');

my $app = builder {
    enable "PopulateENV", app_name => 'mb';

    enable 'Choke::Cache::Filesystem';

    enable
        match_if param('a'),
            'Choke::Requests',
                %{ $$settings{choke}{'status'} }
            ;

    enable
        match_if unchoked(),
            'Choke::Requests',
                %{ $$settings{choke}{'default'} }
            ;

    Download::Builder->new->to_app;

};

Plack::Runner->new->run($app);
