#!/l/local/bin/perl

use strict;
use Getopt::Std;

use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors;

use ToolLib;

sub mass_clone_repo_usage {
    my $s = qq{Usage: mass-clone-repo [options]
                 -s clone under staging area: test, beta-1, beta-2, beta-3 (e.g. /htapps/test.babel)
                    instead of /htapps/user.babel
                 -v verbose
                 -h print help\n};
    return $s;
}

our ($opt_h, $opt_v, $opt_s);
my $ops = getopts('hvs:');

my $help = $opt_h;

if ($help) {
    print mass_clone_repo_usage();
    exit 0;
}

my $clone_options;
$clone_options .= ($opt_v ? ' -v ' : '');
$clone_options .= ($opt_s ? " -s$opt_s " : '');

my @app_list = `cat /htapps/pfarber.babel/mdp-tools/app-list.txt`;
chomp(@app_list);

foreach my $app (@app_list) {
    next unless ($app);
    print `clone-repo $clone_options $app.git`;
}

exit 0;
