#!/usr/bin/env perl

=head1 NAME

validate-app - Simple HTTP 200 check HT application at test.babel in preparation for deployment.

=head1 SYNOPSIS

validate-app app

=head1 OPTIONS

=over 8

=back

=head1 DESCRIPTION

B<validate-app> will attempt a curl on a list of URLs for the app.

=cut
$| = 1;

use strict;
use YAML::Any;
use Getopt::Std;
use IPC::Run;

use lib "/htapps/test.babel/mdp-lib/Utils";
use Vendors;
use File::Basename;
my $LOCATION = dirname(__FILE__);

use ToolLib;

sub validate_app_usage {
    my $s = qq{Usage: validate-app [options] [<app>]
           where <app> is the application.
                 -A all apps
                 -v verbose
                 -L apply debug=local
                 -s staging areas: test (default), beta-1,2,...
                    OR uniqname\n};
    return $s;
}

our ($opt_s, $opt_A, $opt_v, $opt_L);
my $ops = getopts('LAs:v');

my $STAGE = $opt_s || 'test';

my @staging_areas = @ToolLib::all_valid_stages;
if (! grep (/^$STAGE$/, @staging_areas)) {
    PrintN("Invalid staging area=$STAGE\n");
    print validate_app_usage();
    exit 1;
}
    

# If stage==test set correct environment for running scripts at the command line 
if ($STAGE eq 'test') {
    $ENV{SDRROOT} = '/htapps/test.babel';
    delete $ENV{HT_DEV};
}




my $VERBOSE = $opt_v;
my $LOCAL = $opt_L;

my $ALL = $opt_A;
my $app_list = "$LOCATION/../lib/Config/app-list.txt";
my @app_list = `cat $app_list`;
chomp(@app_list);

my @apps;
if ($ALL) {
    @apps = @app_list;
}
else {
    @apps = @ARGV;
    if (! scalar(@apps)) {
        print validate_app_usage();
        exit 1;
    }
}

my ($repo_root, $app_root) = get_HTDE_roots($STAGE);
my $CONFIG = YAML::Any::LoadFile("$LOCATION/../lib/Config/validate-config.yaml");
my $rc = 0;
foreach my $app (@apps) {
    $rc = 0;
    
    PrintY(qq{validate-app checking: $app\n});

    if (! validate_existing_app($repo_root, $app_root, $app)) {
        next;
    }

    if (! grep(/^$app$/, @app_list)) {
        PrintN(qq{App not recognized in $app_list: $app\n});
        next;
    }

    my $url_arr_ref = _get_config_val($app);

    if (! $url_arr_ref) {
        print("\t$app: no test configured\n");
        next;
    }

    foreach my $url (@$url_arr_ref) {
        $url =~ s,__CGI__,cgi,g;

        if ($url =~ m,EMPTY_CACHE,) {
            $rc ||= _empty_cache();
        }
        elsif ($url =~ m,^http,) {
            $rc ||= _test_url($app, $url);
        }
        else {
            $rc ||= _test_cmd($app, $url);
        }

        last if ($rc > 0);
    }
}

exit $rc;


# ---------------------------------------------------------------------

=item Name

Description

=cut

# ---------------------------------------------------------------------
sub _test_url {
    my $app = shift;
    my $url = shift;

    $url =~ s,__URL_STAGE__,$STAGE.babel,g;

    if ($LOCAL) {
        $url =~ s,__LOCAL__,debug=local,;
    }
    else {
        $url =~ s,__LOCAL__,,;
    }

    my $rc = 0;
    my @accepted_statuses = ('200', '301', '302');

    print("app=$app "); print(" URL=$url ... ");

    my $status = `curl --silent --write-out %{http_code} '$url' -o /dev/null`;
    if ($? > 0) {
        my $sysval = $? >> 8;
        my $msg = _get_curl_errmsg($sysval);
        PrintN("curl fail: $sysval: $msg\n");
        $rc = 1;
    }
    else {
        if (grep(/^$status$/, @accepted_statuses)) {
            PrintY("OK [$status]\n");
        }
        else {
            PrintN("HTTP status fail [$status]\n");
            $rc =1 ;
        }
    }

    return $rc;
}


# ---------------------------------------------------------------------

=item _test_cmd

Description

=cut

# ---------------------------------------------------------------------
sub _test_cmd {
    my $app = shift;
    my $cmd = shift;

    $cmd =~ s,__CMD_STAGE__,$STAGE.babel,g;

    if ($LOCAL) {
        $cmd =~ s,__LOCAL__,debug=local,;
    }
    else {
        $cmd =~ s,__LOCAL__,,;
    }

    $cmd =~ s,-full,,;

    my $rc = 0;
    my @accepted_exits = ('0', '1', '4');

    print("app=$app "); print(" CMD=$cmd ... ");

    if ($VERBOSE) {
        print `$cmd`;
    }
    else {
        print `$cmd > /dev/null 2>&1`;
    }

    my $exitval = $? >> 8;
    my $result = grep(/$exitval/, @accepted_exits);

    if ($result) {
        PrintY("OK [$exitval]\n");
    }
    else {
        PrintN("cmd fail: [$exitval]\n");
        $rc = 1 ;
    }

    return $rc;
}


# ---------------------------------------------------------------------

=item Name

Description

=cut

# ---------------------------------------------------------------------
sub _empty_cache {

    my $rc = 0;

    print("Emptying cache ... ");
    `rm -rf /htapps/test.babel/cache-full/*`;
    if ($? > 0) {
        PrintN("Cache not cleared\n");
        $rc = 1;
    }
    else {
        PrintY("OK\n");
    }

    return $rc;
}

# ---------------------------------------------------------------------

=item Name

Description

=cut

# ---------------------------------------------------------------------
sub _get_config_val {
    my ($key, $sub_1_key) = @_;

    if ($sub_1_key) {
        return $CONFIG->{$key}{$sub_1_key};
    }
    else {
        return $CONFIG->{$key};
    }
}

# ---------------------------------------------------------------------

=item Name

Description

=cut

# ---------------------------------------------------------------------
sub _get_curl_errmsg {
    my $sysval = shift;
    my %msghash =
      (
       '1' => 'Unsupported protocol. This build of curl has no support for this protocol.',
       '2' => 'Failed to initialize.',
       '3' => 'URL malformat. The syntax was not correct.',
       '4' => 'URL user malformatted. The user-part of the URL syntax was not correct.',
       '5' => 'Couldn’t resolve proxy. The given proxy host could not be resolved.',
       '6' => 'Couldn’t resolve host. The given remote host was not resolved.',
       '7' => 'Failed to connect to host.',
       '8' => 'FTP weird server reply. The server sent data curl couldn’t parse.',
       '9' => 'FTP access denied. The server denied login or denied access to the particular resource or directory you wanted to reach. Most often you tried  to  change to a directory that doesn’t exist',
       '10' => 'FTP user/password incorrect. Either one or both were not accepted by the server.',
       '11' => 'FTP weird PASS reply. Curl couldn’t parse the reply sent to the PASS request.',
       '12' => 'FTP weird USER reply. Curl couldn’t parse the reply sent to the USER request.',
       '13' => 'FTP weird PASV reply, Curl couldn’t parse the reply sent to the PASV request.',
       '14' => 'FTP weird 227 format. Curl couldn’t parse the 227-line the server sent.',
       '15' => 'FTP can’t get host. Couldn’t resolve the host IP we got in the 227-line.',
       '16' => 'FTP can’t reconnect. Couldn’t connect to the host we got in the 227-line.',
       '17' => 'FTP couldn’t set binary. Couldn’t change transfer method to binary.',
       '18' => 'Partial file. Only a part of the file was transferred.',
       '19' => 'FTP couldn’t download/access the given file, the RETR (or similar) command failed.',
       '20' => 'FTP write error. The transfer was reported bad by the server.',
       '21' => 'FTP quote error. A quote command returned error from the server.',
       '22' => 'HTTP  page  not  retrieved.  The requested url was not found or returned another error with the HTTP error code being 400 or above. This return code only appears if -f/--fail is used.',
       '23' => 'Write error. Curl couldn’t write data to a local filesystem or similar.',
       '24' => 'Malformed user. User name badly specified.',
       '25' => 'FTP couldn’t STOR file. The server denied the STOR operation, used for FTP uploading.',
       '26' => 'Read error. Various reading problems.',
       '27' => 'Out of memory. A memory allocation request failed.',
       '28' => 'Operation timeout. The specified time-out period was reached according to the conditions.',
       '29' => 'FTP couldn’t set ASCII. The server returned an unknown reply.',
       '30' => 'FTP PORT failed. The PORT command failed. Not all FTP servers support the PORT command, try doing a transfer using PASV instead!',
       '31' => 'FTP couldn’t use REST. The REST command failed. This command is used for resumed FTP transfers.',
       '32' => 'FTP couldn’t use SIZE. The SIZE command failed. The command is an extension to the original FTP spec RFC 959.',
       '33' => 'HTTP range error. The range "command" didn’t work.',
       '34' => 'HTTP post error. Internal post-request generation error.',
       '35' => 'SSL connect error. The SSL handshaking failed.',
       '36' => 'FTP bad download resume. Couldn’t continue an earlier aborted download.',
       '37' => 'FILE couldn’t read file. Failed to open the file. Permissions?',
       '38' => 'LDAP cannot bind. LDAP bind operation failed.',
       '39' => 'LDAP search failed.',
       '40' => 'Library not found. The LDAP library was not found.',
       '41' => 'Function not found. A required LDAP function was not found.',
       '42' => 'Aborted by callback. An application told curl to abort the operation.',
       '43' => 'Internal error. A function was called with a bad parameter.',
       '44' => 'Internal error. A function was called in a bad order.',
       '45' => 'Interface error. A specified outgoing interface could not be used.',
       '46' => 'Bad password entered. An error was signaled when the password was entered.',
       '47' => 'Too many redirects. When following redirects, curl hit the maximum amount.',
       '48' => 'Unknown TELNET option specified.',
       '49' => 'Malformed telnet option.',
       '51' => 'The remote peer’s SSL certificate wasn’t ok',
       '52' => 'The server didn’t reply anything, which here is considered an error.',
       '53' => 'SSL crypto engine not found',
       '54' => 'Cannot set SSL crypto engine as default',
       '55' => 'Failed sending network data',
       '56' => 'Failure in receiving network data',
       '57' => 'Share is in use (internal error)',
       '58' => 'Problem with the local certificate',
       '59' => 'Couldn’t use specified SSL cipher',
       '60' => 'Problem with the CA cert (path? permission?)',
       '61' => 'Unrecognized transfer encoding',
       '62' => 'Invalid LDAP URL',
       '63' => 'Maximum file size exceeded',
       '64' => 'Requested FTP SSL level failed',
       '65' => 'Sending the data requires a rewind that failed',
       '66' => 'Failed to initialise SSL Engine',
       '67' => 'User, password or similar was not accepted and curl failed to login',
       '68' => 'File not found on TFTP server',
       '69' => 'Permission problem on TFTP server',
       '70' => 'Out of disk space on TFTP server',
       '71' => 'Illegal TFTP operation',
       '72' => 'Unknown TFTP transfer ID',
       '73' => 'File already exists (TFTP)',
       '74' => 'No such user (TFTP)',
       '75' => 'Character conversion failed',
       '76' => 'Character conversion functions required',
      );
    return $msghash{$sysval};
}


__END__;
