#!/usr/bin/env perl

=head1 NAME

kgs

=head1 DESCRIPTION

This program is the application to: 

(1) Provide Data API (htd) users with an oauth_consumer_key and
oauth_consumer_secret.  Data API users supply a name, organization and
valid email address to which we mail a confirmation link the
registrant can follow to receive and activate their
keys. [/kgs/request /kgs/register /kgs/confirm]

(2) Record the userid (REMOTE_USER) of Data API Client (htdc) users
auto-register them so that the Data API client has an access_key for
them based on their authentication credential.  The user is redirected
to the wayf if xes is not authenticated. [/kgs/authed]

So in the ht.htd_authentication table there are two colums:

email: the email addresses to which we mailed confirmation links for
key provision to developers.  These email addresses can be used to
update developers on changes to Data API versions.

userid: authentication credentials for Data API Client users.  Data
API changes are opaquee to client users.

=head1 SYNOPSIS

http://babel.hathitrust.org/cgi/kgs/request
http://babel.hathitrust.org/cgi/kgs/confirm

From the command line or debugger

$ /htapps/pfarber.babel/kgs/cgi/kgs /request? 

=cut

use warnings;
use strict;

BEGIN {
    ## $ENV{DEBUG_LOCAL} = 1;
}

# ----------------------------------------------------------------------
# Set up paths for local libraries -- must come first
# ----------------------------------------------------------------------
use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors;

use CGI;

use Context;
use Database;
use Utils;
use MdpConfig;
use Session;
use Auth::Auth;

use KGS;
use KGS_Db;


# make sure cache files/dirs are group writable
umask 0002;

# MDP stuff
my $C = new Context;

# configuration
my $config = new MdpConfig(
                           Utils::get_uber_config_path('kgs'),
                           $ENV{SDRROOT} . "/kgs/lib/Config/global.conf",
                           $ENV{SDRROOT} . "/kgs/lib/Config/local.conf"
                          );
$C->set_object('MdpConfig', $config);

# Database connection
my $db = new Database('ht_web');
$C->set_object('Database', $db);
my $dbh = $db->get_DBH();

# get path_info + query_string from command line
my $Q = CGI->new();
my $action = $Q->param('action');
if ($action) {
    $Q->delete('action');
    $Q->path_info($action);
}

my $app = KGS->new(
                   QUERY  => $Q,
                   PARAMS => { 
                              '_context' => $C, 
                              '_dbh'     => $dbh, 
                             }
                  );
$app->run();

1;

__END__

=head1 AUTHOR

Phillip Farber, University of Michigan, pfarber@umich.edu

=head1 COPYRIGHT

Copyright 2011 ©, The Regents of The University of Michigan, All Rights Reserved

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject
to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

=cut
