#!/l/local/bin/perl

=head1 NAME

check-shards

=head1 USAGE

% check-shards -r run -N num_segments

=head1 DESCRIPTION

Must be run on a machine where shards in the filesystem are visible.
Checks to make sure that the number of segments in each shard is at
least 1 and no more than its arg.

=head1 OPTIONS

=over 8

=item -

see help

=back

=cut

# ----------------------------------------------------------------------
# Set up paths for libraries
# ----------------------------------------------------------------------
BEGIN {
    use Vendors;
    use lib vendor_libs();
}

use strict;

# Perl
use Getopt::Std;

# App
use Utils;
use Debug::DUtils;

use Context;
use MdpConfig;

# Local 
use SLIP_Utils::Common;
use SLIP_Utils::States;

# Flush i/o
$| = 1;

sub ck_usage {
    my $s .= qq{Usage: check-shards-j -r run -N num_segments\n};
    return $s;
}

our ($opt_r, $opt_N);

my $ops = getopts('r:N:');

my $INTERACTIVE = $ENV{'TERM'};

my $RUN = $opt_r; # Required
if (! $RUN) {
    my $s = qq{run (-r) parameter missing } . ck_usage();
    my $rc = $SLIP_Utils::States::RC_BAD_ARGS;
    __output($s);
    __non_interactive_err_output($rc, $s);

    exit $rc;
}

my $NUMSEGS = $opt_N; # Required
if (! defined($NUMSEGS)) {
    my $s = qq{num_segments (-N) parameter missing } . ck_usage();
    my $rc = $SLIP_Utils::States::RC_BAD_ARGS;
    __output($s);
    __non_interactive_err_output($rc, $s);

    exit $rc;
}
elsif ($NUMSEGS < 1) {
    my $s = qq{num_segments (-N) parameter must be > 0 } . ck_usage();
    my $rc = $SLIP_Utils::States::RC_BAD_ARGS;
    __output($s);
    __non_interactive_err_output($rc, $s);

    exit $rc;
}    

my $run_configfile = $ENV{'SDRROOT'} . qq{/slip/index/Config/run-$RUN.conf};
my $common_configfile = $ENV{'SDRROOT'} . qq{/slip/index/Config/common.conf};
my $config = new MdpConfig($common_configfile, $run_configfile);

my $rc = 0;
my $errs = '';

my @num_shards_list = $config->get('num_shards_list');
my $shared_solr_home_dir = $config->get('shared_solr_home_dir');
foreach my $shard (@num_shards_list) {
    my $index_dir = qq{$shared_solr_home_dir/$shard/data/index};
    my $num_segments = `ls $index_dir/*.prx  2> /dev/null | wc -l`;
    chomp($num_segments);
    
    if ($num_segments < 1) {
        my $s = qq{shard=$shard dir=$index_dir segments < 1\n};
        __output($s);
        $errs .= $s;
        $rc++;
    }
    elsif ($num_segments > $NUMSEGS) {
        my $s = qq{shard=$shard dir=$index_dir segments=$num_segments (exceeds $NUMSEGS)\n};
        __output($s);
        $errs .= $s;
        $rc++;
    }
    else {
        __output(qq{shard=$shard dir=$index_dir segments=$num_segments (OK)\n});
    }
}

__non_interactive_err_output($rc, $errs);

exit $rc;

1;


=head1 AUTHOR

Phillip Farber, University of Michigan, pfarber@umich.edu

=head1 COPYRIGHT

Copyright 2009 ©, The Regents of The University of Michigan, All Rights Reserved

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject
to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

=cut



