#!/usr/bin/env perl

use strict;
use warnings;

BEGIN {
    ## $ENV{DEBUG_LOCAL} = 1;
}
use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors;

use CGI;

use Context;
use Debug::DUtils;
use Auth::ACL;
use Database;
use MdpConfig;
use Session;
use Auth::Auth;



my $C = new Context;

# CGI
my $cgi = new CGI;
Utils::clean_cgi_params($cgi);
$C->set_object('CGI', $cgi);

my $config = new MdpConfig(Utils::get_uber_config_path('whoami'));
$C->set_object('MdpConfig', $config);

# Database connection
my $db = new Database('ht_web');
$C->set_object('Database', $db);

Debug::DUtils::setup_debug_environment();

# Auth
my $auth = new Auth::Auth($C);
$C->set_object('Auth', $auth);

my $developement = 1 if ($ENV{HT_DEV} || (Auth::ACL::a_Authorized( {role => 'superuser'} ) && DEBUG('super')));
$developement = 0 if ( DEBUG('ord') );

# --- App ---
#
print CGI::header();
print qq{<body style="margin:3em;width:50%">};

print qq{
    <div>
      <!-- header -->
      <div>
        <div>
          <div>
            <div>
              <a id="htlogo" href="http://www.hathitrust.org">
                <img src="/register/graphics/HathiTrustDL_logo.png" alt="Hathi Trust Logo" /></a>
            </div>
          </div>
        </div>
      </div>
    </div> };

if (defined $ENV{REMOTE_USER} && $ENV{REMOTE_USER}) {
    if ($developement) {
        print Debug::DUtils::print_env($ENV{TERM} ? '' : 'html');
    }
    else {
        my $remote_addr = $ENV{REMOTE_ADDR};
        my $country = get_geoip($remote_addr);
        my $client_host = `host $remote_addr`;
        chomp($client_host);

        my $auth_type = lc $ENV{AUTH_TYPE};

        my $remote_user = $ENV{REMOTE_USER};
        my $li;

        if ( $auth_type eq 'shibboleth' && ! Utils::is_cosign_active() ) {
          my $shibboleth_remote_user = $remote_user;
          $remote_user = Utils::Get_Legacy_Remote_User();
          $li = qq{<li>SHIBBOLETH IDENTITY = "$shibboleth_remote_user" (for University of Michigan)</li>};
        }

        print qq{<p>Here are your credentials as we see them from your login.</p>};
        print qq{<ul>
                   <li>REMOTE_USER = "$remote_user" or possibly forwarded for: "$ENV{HTTP_X_FORWARDED_FOR}"</li>
                   $li
                   <li>REMOTE_ADDR = "$remote_addr" <br/>&nbsp;&nbsp;country = "$country" <br/>&nbsp;&nbsp;USER AGENT host="$client_host"</li>
                   <li>REMOTE_REALM = "$ENV{REMOTE_REALM}"</li>
                   <li>AUTH_TYPE = "$ENV{AUTH_TYPE}"</li>
                   <li>HTTP_USER_AGENT = "$ENV{HTTP_USER_AGENT}"</li>
                   <li>HTTP_HOST = "$ENV{HTTP_HOST}"</li>
                   <li>SDRINST = "$ENV{SDRINST}"</li>
                   <li>SDRLIB = "$ENV{SDRLIB}"</li>};

        if ($auth_type eq 'shibboleth') {
            print qq{<li>eduPersonScopedAffiliation = "$ENV{affiliation}"</li>
                     <li>eduPersonPrincipalName = "$ENV{eppn}"</li>
                     <li>displayName = "$ENV{displayName}"</li>
                     <li>entityID = "$ENV{Shib_Identity_Provider}"</li>
                     <li>authenticationMethod = "$ENV{Shib_Authentication_Method}"</li>
                     <li>authnContextClass = "$ENV{Shib_AuthnContext_Class}"</li>};
        }
        print qq{</ul>};
    }

    print q{<p>If you were asked to forward this information to HathiTrust, please attach a screen shot or copy and paste this text to a reply to the support ticket email we sent in response to your request for assistance.</p> };

    print qq{<p>Thank you.</p>};
}
else {
    print q{<p>Greetings,</p><p>You have been directed here to log in.</p><p> You will be sent to the HathiTrust login page from the login link below where you will proceed to your institutional login page and be redirected back to a HathiTrust page where you will be able to view your login credentials.</p>};

    print q{<p>You then have the option to email those credentials to HathiTrust for purposes such as:
 <li>Recovering access to personal collections if you change institutional affiliation</li>
<li>Supporting our staff in setting up your access to materials</li></p>};

    print qq{<p>Please <a href="http://$ENV{HTTP_HOST}/cgi/wayf?target=https%3A%2F%2F$ENV{HTTP_HOST}%2Fcgi%2Fwhoami" id="login-button" class="button log-in"><b>LOG IN</b></a> to HathiTrust start the process.</p>};

    print q{<p>Questions?  Contact us at <a href="mailto:feedback@issues.hathitrust.org">feedback@issues.hathitrust.org</a> };
}
print qq{</body>};

exit 0;

sub get_geoip {
    use Geo::IP;

    my $IP = shift;

    my $geoIp = Geo::IP->new();
    my $countryCode = $geoIp->country_code_by_addr($IP);
    my $countryName = $geoIp->country_name_by_addr($IP);
    return "$countryCode / $countryName";
}
