#!/usr/bin/env perl

=head1 NAME

HathiTrust Repository Data API (htd)

=head1 USAGE

http://babel.hathitrust.org/cgi/htd/<URI>? ... URL parameters ...

=head1 DESCRIPTION

Implementation of REST API to access Hathitrust repository data and
structural/administrative metadata

=head1 OPTIONS

=over 8

=item debug=opt1,opt2,...,optN

Debug options

=back

=cut
umask 0000;

# ----------------------------------------------------------------------
# Set up paths for local libraries -- must come first
# ----------------------------------------------------------------------
use lib "$ENV{SDRROOT}/mdp-lib/Utils";
use Vendors;

use CGI;

# API versions
use constant API_VERSION_1 => 1;
use constant API_VERSION_2 => 2;
our @VERSIONS = (API_VERSION_2, API_VERSION_1);

# ============================ Main ===================================

# Determine which version of API to load and run
our $Q = CGI->new();

# get path_info + query_string from command line
my $action = $Q->param('action');
if ($action) {
    $Q->delete('action');
    $Q->path_info($action);
}

my $API_version = __determineVersion($Q);

unless (defined $API_version) {
    __errorExit($Q, '400 BAD REQUEST Invalid version');
    # NOTREACHED
}

my $classPackage = qq{API::HTD::App::V_${API_version}::Plugin};
my $classPath = __packageToPath($classPackage);

eval {
    require $classPath;
};
if ($@) {
    __errorExit($Q, '500 INTERNAL SERVER ERROR');
    # NOTREACHED
}

my $API_version_instance = $classPackage->new(('CGI' => $Q));

# for Plack/PSGI, return the run instance
my $retval = $API_version_instance->run();
return $retval if ( defined($ENV{'psgi.version'}) );

exit 0;


# ---------------------------------------------------------------------

=item __errorExit

Description

=cut

# ---------------------------------------------------------------------
sub __errorExit {
    my $Q = shift;
    my $msg = shift;

    if ($ENV{HT_DEV}) {
        print $Q->header('text/html');
        print qq{ERROR: $msg $@};
        exit 0;
    }
    else {
        $Q->header(-Status => $msg);
        exit 1;
    }
}

# ---------------------------------------------------------------------

=item __determineVersion

After Nov. 1, 2013 version parameter (v) must be present and must be
2, currently.

=cut

# ---------------------------------------------------------------------
use constant NOV_1_2013 => 1383264000;
sub __determineVersion {
    my $Q = shift;

    my $version;

    if (time() < NOV_1_2013) {
        $version = $Q->param('v') ? $Q->param('v') : API_VERSION_1;
        unless (grep(/^$version$/, @VERSIONS)) {
            return undef;
        }
        # POSSIBLY NOTREACHED
    }
    else {
        $version = $Q->param('v');
        unless ($version == API_VERSION_2) {
            return undef;
        }
        # POSSIBLY NOTREACHED
    }

    return $version;
}

sub __packageToPath {
    my $package = shift;

    my $pathRoot = $ENV{'SDRROOT'} . '/htd/lib/';
    my $path = $pathRoot . $package . '.pm';
    $path =~ s,::,/,g;

    return $path;
}

=head1 AUTHOR

Phillip Farber, University of Michigan, pfarber@umich.edu

=head1 COPYRIGHT

Copyright 2009 ©, The Regents of The University of Michigan, All Rights Reserved

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject
to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

=cut
